services:
  git-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ls1intum/git-container:latest
    environment:
      - DEBUG=true
      - HADES_HELLO_URL=http://hades_hello_1:8080/example.git
      - HADES_HELLO_USERNAME=user
      - HADES_HELLO_PASSWORD=secret
      - HADES_HELLO_PATH=./hello
      - HADES_HELLO_ORDER=1
      - REPOSITORY_DIR=/opt/repositories
    volumes:
      - ./repo:/opt/repositories
