version: '3.7'
services:
  hadesclonecontainer:
    build:
      context: ..
      dockerfile: ./HadesCloneContainer/Dockerfile
    image: ls1intum/hades/hades-git-container
    environment:
      - DEBUG=true
      - HADES_HELLO_URL=http://hades_hello_1:8080/example.git
      - HADES_HELLO_USERNAME=user
      - HADES_HELLO_PASSWORD=secret
      - HADES_HELLO_PATH=./hello
      - HADES_HELLO_ORDER=1
      - REPOSITORY_DIR=/opt/repositories
    volumes:
      - ./repo:/opt/repositories
